apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthcare-apps
  labels:
    app.kubernetes.io/name: appointment-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: healthcare-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: appointment-service
  ports:
    - name: http
      port: 80
      targetPort: http
