apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: healthcare-apps
  labels:
    app.kubernetes.io/name: appointment-service
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: healthcare-platform
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/name: appointment-service
  ports:
    - name: http
      port: 80
      targetPort: http
